/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Login (void)
{
  GtkWidget *Login;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *button1;
  GtkWidget *label4;

  Login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Login), _("Login"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Login), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 128, 56);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 128, 104);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label1 = gtk_label_new (_("Username :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 32, 64);
  gtk_widget_set_size_request (label1, 73, 16);

  label2 = gtk_label_new (_("Password :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 24, 112);
  gtk_widget_set_size_request (label2, 88, 16);

  button1 = gtk_button_new_with_mnemonic (_("Login"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 136, 160);
  gtk_widget_set_size_request (button1, 66, 29);

  label4 = gtk_label_new ("");
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 232, 168);
  gtk_widget_set_size_request (label4, 128, 72);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Login, Login, "Login");
  GLADE_HOOKUP_OBJECT (Login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Login, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Login, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Login, label1, "label1");
  GLADE_HOOKUP_OBJECT (Login, label2, "label2");
  GLADE_HOOKUP_OBJECT (Login, button1, "button1");
  GLADE_HOOKUP_OBJECT (Login, label4, "label4");

  return Login;
}

GtkWidget*
create_Admin (void)
{
  GtkWidget *Admin;
  GtkWidget *notebook1;
  GtkWidget *notebook2;
  GtkWidget *fixed7;
  GtkWidget *treeview1;
  GtkWidget *button8;
  GtkWidget *label55;
  GtkWidget *fixed4;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *erreur_tel;
  GtkWidget *entry15;
  GtkWidget *combobox1;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label18;
  GtkWidget *label17;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label13;
  GtkWidget *combobox2;
  GtkWidget *label12;
  GtkWidget *label23;
  GtkWidget *label47;
  GtkWidget *label19;
  GtkWidget *button11;
  GtkWidget *button13;
  GtkWidget *erreur_taille;
  GtkWidget *erreur_poids;
  GtkWidget *label56;
  GtkWidget *label51;
  GtkWidget *notebook3;
  GtkWidget *fixed8;
  GtkWidget *treeview2;
  GtkWidget *button14;
  GtkWidget *label57;
  GtkWidget *fixed9;
  GtkWidget *entry16;
  GtkWidget *entry17;
  GtkWidget *entry18;
  GtkWidget *entry19;
  GtkWidget *entry22;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *label68;
  GtkWidget *label69;
  GtkWidget *label70;
  GtkWidget *label72;
  GtkWidget *button16;
  GtkWidget *button17;
  GtkWidget *combobox4;
  GtkWidget *erreur;
  GtkWidget *label74;
  GtkWidget *label52;
  GtkWidget *notebook4;
  GtkWidget *fixed10;
  GtkWidget *treeview3;
  GtkWidget *button18;
  GtkWidget *label75;
  GtkWidget *fixed11;
  GtkWidget *entry23;
  GtkWidget *entry24;
  GtkWidget *entry25;
  GtkWidget *entry26;
  GtkWidget *entry27;
  GtkWidget *label80;
  GtkWidget *label81;
  GtkWidget *label84;
  GtkWidget *combobox5;
  GtkWidget *label79;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *label85;
  GtkWidget *button19;
  GtkWidget *button20;
  GtkWidget *erreur1;
  GtkWidget *combobox6;
  GtkWidget *label83;
  GtkWidget *label53;
  GtkWidget *notebook5;
  GtkWidget *fixed12;
  GtkWidget *treeview4;
  GtkWidget *button21;
  GtkWidget *label86;
  GtkWidget *fixed13;
  GtkWidget *entry28;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label89;
  GtkWidget *label90;
  GtkWidget *entry34;
  GtkWidget *label103;
  GtkWidget *label99;
  GtkWidget *label93;
  GtkWidget *label94;
  GtkWidget *label92;
  GtkWidget *label104;
  GtkWidget *label101;
  GtkWidget *button23;
  GtkWidget *button22;
  GtkWidget *erreur2;
  GtkWidget *combobox8;
  GtkWidget *label87;
  GtkWidget *fixed14;
  GtkWidget *button24;
  GtkWidget *NB_M;
  GtkWidget *NB_C;
  GtkWidget *NB_A_F;
  GtkWidget *NB_A_H;
  GtkWidget *NB_A;
  GtkWidget *label88;
  GtkWidget *label54;

  Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Admin), _("Admin"));
  gtk_window_set_position (GTK_WINDOW (Admin), GTK_WIN_POS_CENTER);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (Admin), notebook1);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook2);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed7);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview1, 24, 0);
  gtk_widget_set_size_request (treeview1, 752, 368);

  button8 = gtk_button_new_with_mnemonic (_("Rafra\303\256chir La Liste"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed7), button8, 312, 368);
  gtk_widget_set_size_request (button8, 152, 56);

  label55 = gtk_label_new (_("Liste Des Adherents"));
  gtk_widget_show (label55);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label55);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed4);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed4), entry3, 272, 48);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed4), entry4, 272, 88);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 272, 208);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 272, 168);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 272, 248);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 272, 288);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1, 296, 336);
  gtk_widget_set_size_request (spinbutton1, 48, 24);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spinbutton1), GTK_UPDATE_IF_VALID);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 408, 336);
  gtk_widget_set_size_request (spinbutton2, 48, 24);

  spinbutton3_adj = gtk_adjustment_new (2018, 0, 2018, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 528, 336);
  gtk_widget_set_size_request (spinbutton3, 64, 24);

  erreur_tel = gtk_label_new ("");
  gtk_widget_show (erreur_tel);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur_tel, 456, 160);
  gtk_widget_set_size_request (erreur_tel, 128, 25);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed4), entry15, 272, 8);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox1, 272, 376);
  gtk_widget_set_size_request (combobox1, 128, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("3 Mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("6 Mois"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("1 Ann\303\251e"));

  label20 = gtk_label_new (_("Jour"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 232, 336);
  gtk_widget_set_size_request (label20, 65, 24);

  label21 = gtk_label_new (_("Mois"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 352, 336);
  gtk_widget_set_size_request (label21, 56, 24);

  label22 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 464, 336);
  gtk_widget_set_size_request (label22, 56, 24);

  label18 = gtk_label_new (_("Poids"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 184, 288);
  gtk_widget_set_size_request (label18, 56, 24);

  label17 = gtk_label_new (_("Taille"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 184, 248);
  gtk_widget_set_size_request (label17, 56, 24);

  label14 = gtk_label_new (_("Email"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 176, 208);
  gtk_widget_set_size_request (label14, 64, 24);

  label15 = gtk_label_new (_("T\303\251l\303\251phone"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 176, 168);
  gtk_widget_set_size_request (label15, 88, 24);

  label16 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 184, 128);
  gtk_widget_set_size_request (label16, 56, 24);

  label13 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 176, 88);
  gtk_widget_set_size_request (label13, 64, 24);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox2, 272, 128);
  gtk_widget_set_size_request (combobox2, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Femme"));

  label12 = gtk_label_new (_("Nom"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed4), label12, 184, 48);
  gtk_widget_set_size_request (label12, 56, 24);

  label23 = gtk_label_new (_("Abonnement"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 144, 376);
  gtk_widget_set_size_request (label23, 112, 32);
  gtk_misc_set_alignment (GTK_MISC (label23), 0.56, 0.5);
  gtk_misc_set_padding (GTK_MISC (label23), 2, 4);

  label47 = gtk_label_new (_("ID"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed4), label47, 184, 8);
  gtk_widget_set_size_request (label47, 64, 25);

  label19 = gtk_label_new (_("Date de Naissance"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 88, 336);
  gtk_widget_set_size_request (label19, 152, 24);

  button11 = gtk_button_new_with_mnemonic (_("Ajouter/Modifier"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed4), button11, 352, 440);
  gtk_widget_set_size_request (button11, 144, 40);

  button13 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed4), button13, 208, 440);
  gtk_widget_set_size_request (button13, 98, 37);

  erreur_taille = gtk_label_new ("");
  gtk_widget_show (erreur_taille);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur_taille, 464, 240);
  gtk_widget_set_size_request (erreur_taille, 160, 32);

  erreur_poids = gtk_label_new ("");
  gtk_widget_show (erreur_poids);
  gtk_fixed_put (GTK_FIXED (fixed4), erreur_poids, 464, 280);
  gtk_widget_set_size_request (erreur_poids, 168, 32);

  label56 = gtk_label_new (_("Gestion Des Adherents"));
  gtk_widget_show (label56);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label56);

  label51 = gtk_label_new (_("Adherents"));
  gtk_widget_show (label51);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label51);

  notebook3 = gtk_notebook_new ();
  gtk_widget_show (notebook3);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook3);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed8);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview2, 208, 64);
  gtk_widget_set_size_request (treeview2, 328, 224);

  button14 = gtk_button_new_with_mnemonic (_("Rafra\303\256chir La Liste"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed8), button14, 312, 368);
  gtk_widget_set_size_request (button14, 152, 56);

  label57 = gtk_label_new (_("Liste Des Coaches"));
  gtk_widget_show (label57);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 0), label57);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook3), fixed9);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed9), entry16, 272, 48);
  gtk_widget_set_size_request (entry16, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed9), entry17, 272, 88);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed9), entry18, 272, 208);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed9), entry19, 272, 168);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry22 = gtk_entry_new ();
  gtk_widget_show (entry22);
  gtk_fixed_put (GTK_FIXED (fixed9), entry22, 272, 8);
  gtk_widget_set_size_request (entry22, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  label66 = gtk_label_new (_("Email"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed9), label66, 176, 208);
  gtk_widget_set_size_request (label66, 64, 24);

  label67 = gtk_label_new (_("T\303\251l\303\251phone"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed9), label67, 176, 168);
  gtk_widget_set_size_request (label67, 88, 24);

  label68 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed9), label68, 184, 128);
  gtk_widget_set_size_request (label68, 56, 24);

  label69 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed9), label69, 176, 88);
  gtk_widget_set_size_request (label69, 64, 24);

  label70 = gtk_label_new (_("Nom"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed9), label70, 184, 48);
  gtk_widget_set_size_request (label70, 56, 24);

  label72 = gtk_label_new (_("ID"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed9), label72, 184, 8);
  gtk_widget_set_size_request (label72, 64, 25);

  button16 = gtk_button_new_with_mnemonic (_("Ajouter/Modifier"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed9), button16, 320, 280);
  gtk_widget_set_size_request (button16, 144, 40);

  button17 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed9), button17, 160, 280);
  gtk_widget_set_size_request (button17, 98, 37);

  combobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox4, 272, 128);
  gtk_widget_set_size_request (combobox4, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4), _("Femme"));

  erreur = gtk_label_new ("");
  gtk_widget_show (erreur);
  gtk_fixed_put (GTK_FIXED (fixed9), erreur, 472, 208);
  gtk_widget_set_size_request (erreur, 168, 24);

  label74 = gtk_label_new (_("Gestion Des Coaches"));
  gtk_widget_show (label74);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook3), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook3), 1), label74);

  label52 = gtk_label_new (_("Coachs"));
  gtk_widget_show (label52);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label52);

  notebook4 = gtk_notebook_new ();
  gtk_widget_show (notebook4);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook4);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed10);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview3, 216, 56);
  gtk_widget_set_size_request (treeview3, 328, 232);

  button18 = gtk_button_new_with_mnemonic (_("Rafra\303\256chir La Liste"));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed10), button18, 312, 368);
  gtk_widget_set_size_request (button18, 152, 56);

  label75 = gtk_label_new (_("Staff M\303\251dical"));
  gtk_widget_show (label75);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), label75);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook4), fixed11);

  entry23 = gtk_entry_new ();
  gtk_widget_show (entry23);
  gtk_fixed_put (GTK_FIXED (fixed11), entry23, 272, 48);
  gtk_widget_set_size_request (entry23, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry23), 8226);

  entry24 = gtk_entry_new ();
  gtk_widget_show (entry24);
  gtk_fixed_put (GTK_FIXED (fixed11), entry24, 272, 88);
  gtk_widget_set_size_request (entry24, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24), 8226);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_fixed_put (GTK_FIXED (fixed11), entry25, 272, 208);
  gtk_widget_set_size_request (entry25, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed11), entry26, 272, 168);
  gtk_widget_set_size_request (entry26, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed11), entry27, 272, 8);
  gtk_widget_set_size_request (entry27, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  label80 = gtk_label_new (_("Nom"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed11), label80, 184, 48);
  gtk_widget_set_size_request (label80, 56, 24);

  label81 = gtk_label_new (_("ID"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed11), label81, 184, 8);
  gtk_widget_set_size_request (label81, 64, 25);

  label84 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed11), label84, 184, 128);
  gtk_widget_set_size_request (label84, 56, 24);

  combobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5);
  gtk_fixed_put (GTK_FIXED (fixed11), combobox5, 272, 128);
  gtk_widget_set_size_request (combobox5, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5), _("Femme"));

  label79 = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed11), label79, 176, 88);
  gtk_widget_set_size_request (label79, 64, 24);

  label76 = gtk_label_new (_("Email"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed11), label76, 176, 208);
  gtk_widget_set_size_request (label76, 64, 24);

  label77 = gtk_label_new (_("T\303\251l\303\251phone"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed11), label77, 168, 168);
  gtk_widget_set_size_request (label77, 88, 24);

  label85 = gtk_label_new (_("Role"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed11), label85, 168, 248);
  gtk_widget_set_size_request (label85, 88, 24);

  button19 = gtk_button_new_with_mnemonic (_("Ajouter/Modifier"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed11), button19, 320, 304);
  gtk_widget_set_size_request (button19, 144, 40);

  button20 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed11), button20, 160, 304);
  gtk_widget_set_size_request (button20, 98, 37);

  erreur1 = gtk_label_new ("");
  gtk_widget_show (erreur1);
  gtk_fixed_put (GTK_FIXED (fixed11), erreur1, 472, 208);
  gtk_widget_set_size_request (erreur1, 168, 24);

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed11), combobox6, 272, 248);
  gtk_widget_set_size_request (combobox6, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Kin\303\251sith\303\251rapeute"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("M\303\251decin_Nutritioniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("Di\303\251ticien"));

  label83 = gtk_label_new (_("Gestion Du Staff"));
  gtk_widget_show (label83);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), label83);

  label53 = gtk_label_new (_("Espace M\303\251dical"));
  gtk_widget_show (label53);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label53);

  notebook5 = gtk_notebook_new ();
  gtk_widget_show (notebook5);
  gtk_container_add (GTK_CONTAINER (notebook1), notebook5);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook5), fixed12);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview4, 216, 56);
  gtk_widget_set_size_request (treeview4, 328, 240);

  button21 = gtk_button_new_with_mnemonic (_("Rafra\303\256chir La Liste"));
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed12), button21, 312, 368);
  gtk_widget_set_size_request (button21, 152, 56);

  label86 = gtk_label_new (_("Evenements"));
  gtk_widget_show (label86);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 0), label86);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook5), fixed13);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed13), entry28, 272, 48);
  gtk_widget_set_size_request (entry28, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton4, 296, 184);
  gtk_widget_set_size_request (spinbutton4, 48, 24);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (spinbutton4), GTK_UPDATE_IF_VALID);

  spinbutton5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton5, 392, 184);
  gtk_widget_set_size_request (spinbutton5, 48, 24);

  spinbutton6_adj = gtk_adjustment_new (2018, 2018, 2022, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton6, 512, 184);
  gtk_widget_set_size_request (spinbutton6, 64, 24);

  label89 = gtk_label_new ("");
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed13), label89, 456, 160);
  gtk_widget_set_size_request (label89, 128, 25);

  label90 = gtk_label_new ("");
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed13), label90, 464, 240);
  gtk_widget_set_size_request (label90, 128, 24);

  entry34 = gtk_entry_new ();
  gtk_widget_show (entry34);
  gtk_fixed_put (GTK_FIXED (fixed13), entry34, 272, 8);
  gtk_widget_set_size_request (entry34, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry34), 8226);

  label103 = gtk_label_new (_("ID"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed13), label103, 184, 8);
  gtk_widget_set_size_request (label103, 64, 25);

  label99 = gtk_label_new (_("Type"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed13), label99, 184, 88);
  gtk_widget_set_size_request (label99, 56, 24);

  label93 = gtk_label_new (_("Mois"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed13), label93, 344, 184);
  gtk_widget_set_size_request (label93, 56, 24);

  label94 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed13), label94, 448, 184);
  gtk_widget_set_size_request (label94, 56, 24);

  label92 = gtk_label_new (_("Jour"));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed13), label92, 224, 184);
  gtk_widget_set_size_request (label92, 65, 24);

  label104 = gtk_label_new (_("Date "));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed13), label104, 88, 184);
  gtk_widget_set_size_request (label104, 152, 24);

  label101 = gtk_label_new (_("Nom de l'\303\251v\303\250nement"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed13), label101, 104, 48);
  gtk_widget_set_size_request (label101, 152, 32);

  button23 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed13), button23, 224, 256);
  gtk_widget_set_size_request (button23, 98, 37);

  button22 = gtk_button_new_with_mnemonic (_("Ajouter/Modifier"));
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed13), button22, 360, 256);
  gtk_widget_set_size_request (button22, 144, 40);

  erreur2 = gtk_label_new ("");
  gtk_widget_show (erreur2);
  gtk_fixed_put (GTK_FIXED (fixed13), erreur2, 496, 112);
  gtk_widget_set_size_request (erreur2, 112, 25);

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed13), combobox8, 272, 88);
  gtk_widget_set_size_request (combobox8, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Offre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Cours_Sp\303\251cial"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Autre"));

  label87 = gtk_label_new (_("Gestion Des Evenements"));
  gtk_widget_show (label87);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 1), label87);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook5), fixed14);

  button24 = gtk_button_new_with_mnemonic (_("Calculer les statistiques"));
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed14), button24, 272, 288);
  gtk_widget_set_size_request (button24, 192, 40);

  NB_M = gtk_label_new (_("Nombre de staff m\303\251dical :"));
  gtk_widget_show (NB_M);
  gtk_fixed_put (GTK_FIXED (fixed14), NB_M, 112, 208);
  gtk_widget_set_size_request (NB_M, 336, 48);
  gtk_misc_set_alignment (GTK_MISC (NB_M), 0.5, 0.47);

  NB_C = gtk_label_new (_("Nombre de coaches :"));
  gtk_widget_show (NB_C);
  gtk_fixed_put (GTK_FIXED (fixed14), NB_C, 136, 160);
  gtk_widget_set_size_request (NB_C, 256, 40);

  NB_A_F = gtk_label_new (_("Femmes :"));
  gtk_widget_show (NB_A_F);
  gtk_fixed_put (GTK_FIXED (fixed14), NB_A_F, 144, 96);
  gtk_widget_set_size_request (NB_A_F, 232, 40);

  NB_A_H = gtk_label_new (_("Hommes :"));
  gtk_widget_show (NB_A_H);
  gtk_fixed_put (GTK_FIXED (fixed14), NB_A_H, 384, 96);
  gtk_widget_set_size_request (NB_A_H, 224, 32);

  NB_A = gtk_label_new (_("Nombre D'adh\303\251rents"));
  gtk_widget_show (NB_A);
  gtk_fixed_put (GTK_FIXED (fixed14), NB_A, 96, 32);
  gtk_widget_set_size_request (NB_A, 217, 40);

  label88 = gtk_label_new (_("Statistiques"));
  gtk_widget_show (label88);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 2), label88);

  label54 = gtk_label_new (_("Gestion Du Site"));
  gtk_widget_show (label54);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label54);

  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) label55, "activate_link",
                    G_CALLBACK (on_label55_activate_link),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) label57, "activate_link",
                    G_CALLBACK (on_label55_activate_link),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);
  g_signal_connect ((gpointer) label75, "activate_link",
                    G_CALLBACK (on_label55_activate_link),
                    NULL);
  g_signal_connect ((gpointer) button19, "clicked",
                    G_CALLBACK (on_button19_clicked),
                    NULL);
  g_signal_connect ((gpointer) button20, "clicked",
                    G_CALLBACK (on_button20_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21, "clicked",
                    G_CALLBACK (on_button21_clicked),
                    NULL);
  g_signal_connect ((gpointer) button23, "clicked",
                    G_CALLBACK (on_button23_clicked),
                    NULL);
  g_signal_connect ((gpointer) button22, "clicked",
                    G_CALLBACK (on_button22_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24, "clicked",
                    G_CALLBACK (on_button24_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Admin, Admin, "Admin");
  GLADE_HOOKUP_OBJECT (Admin, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Admin, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (Admin, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Admin, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Admin, button8, "button8");
  GLADE_HOOKUP_OBJECT (Admin, label55, "label55");
  GLADE_HOOKUP_OBJECT (Admin, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Admin, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Admin, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Admin, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Admin, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (Admin, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (Admin, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Admin, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Admin, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Admin, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Admin, erreur_tel, "erreur_tel");
  GLADE_HOOKUP_OBJECT (Admin, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (Admin, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (Admin, label20, "label20");
  GLADE_HOOKUP_OBJECT (Admin, label21, "label21");
  GLADE_HOOKUP_OBJECT (Admin, label22, "label22");
  GLADE_HOOKUP_OBJECT (Admin, label18, "label18");
  GLADE_HOOKUP_OBJECT (Admin, label17, "label17");
  GLADE_HOOKUP_OBJECT (Admin, label14, "label14");
  GLADE_HOOKUP_OBJECT (Admin, label15, "label15");
  GLADE_HOOKUP_OBJECT (Admin, label16, "label16");
  GLADE_HOOKUP_OBJECT (Admin, label13, "label13");
  GLADE_HOOKUP_OBJECT (Admin, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (Admin, label12, "label12");
  GLADE_HOOKUP_OBJECT (Admin, label23, "label23");
  GLADE_HOOKUP_OBJECT (Admin, label47, "label47");
  GLADE_HOOKUP_OBJECT (Admin, label19, "label19");
  GLADE_HOOKUP_OBJECT (Admin, button11, "button11");
  GLADE_HOOKUP_OBJECT (Admin, button13, "button13");
  GLADE_HOOKUP_OBJECT (Admin, erreur_taille, "erreur_taille");
  GLADE_HOOKUP_OBJECT (Admin, erreur_poids, "erreur_poids");
  GLADE_HOOKUP_OBJECT (Admin, label56, "label56");
  GLADE_HOOKUP_OBJECT (Admin, label51, "label51");
  GLADE_HOOKUP_OBJECT (Admin, notebook3, "notebook3");
  GLADE_HOOKUP_OBJECT (Admin, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Admin, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (Admin, button14, "button14");
  GLADE_HOOKUP_OBJECT (Admin, label57, "label57");
  GLADE_HOOKUP_OBJECT (Admin, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Admin, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (Admin, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (Admin, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (Admin, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (Admin, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (Admin, label66, "label66");
  GLADE_HOOKUP_OBJECT (Admin, label67, "label67");
  GLADE_HOOKUP_OBJECT (Admin, label68, "label68");
  GLADE_HOOKUP_OBJECT (Admin, label69, "label69");
  GLADE_HOOKUP_OBJECT (Admin, label70, "label70");
  GLADE_HOOKUP_OBJECT (Admin, label72, "label72");
  GLADE_HOOKUP_OBJECT (Admin, button16, "button16");
  GLADE_HOOKUP_OBJECT (Admin, button17, "button17");
  GLADE_HOOKUP_OBJECT (Admin, combobox4, "combobox4");
  GLADE_HOOKUP_OBJECT (Admin, erreur, "erreur");
  GLADE_HOOKUP_OBJECT (Admin, label74, "label74");
  GLADE_HOOKUP_OBJECT (Admin, label52, "label52");
  GLADE_HOOKUP_OBJECT (Admin, notebook4, "notebook4");
  GLADE_HOOKUP_OBJECT (Admin, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Admin, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (Admin, button18, "button18");
  GLADE_HOOKUP_OBJECT (Admin, label75, "label75");
  GLADE_HOOKUP_OBJECT (Admin, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (Admin, entry23, "entry23");
  GLADE_HOOKUP_OBJECT (Admin, entry24, "entry24");
  GLADE_HOOKUP_OBJECT (Admin, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (Admin, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (Admin, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (Admin, label80, "label80");
  GLADE_HOOKUP_OBJECT (Admin, label81, "label81");
  GLADE_HOOKUP_OBJECT (Admin, label84, "label84");
  GLADE_HOOKUP_OBJECT (Admin, combobox5, "combobox5");
  GLADE_HOOKUP_OBJECT (Admin, label79, "label79");
  GLADE_HOOKUP_OBJECT (Admin, label76, "label76");
  GLADE_HOOKUP_OBJECT (Admin, label77, "label77");
  GLADE_HOOKUP_OBJECT (Admin, label85, "label85");
  GLADE_HOOKUP_OBJECT (Admin, button19, "button19");
  GLADE_HOOKUP_OBJECT (Admin, button20, "button20");
  GLADE_HOOKUP_OBJECT (Admin, erreur1, "erreur1");
  GLADE_HOOKUP_OBJECT (Admin, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (Admin, label83, "label83");
  GLADE_HOOKUP_OBJECT (Admin, label53, "label53");
  GLADE_HOOKUP_OBJECT (Admin, notebook5, "notebook5");
  GLADE_HOOKUP_OBJECT (Admin, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Admin, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (Admin, button21, "button21");
  GLADE_HOOKUP_OBJECT (Admin, label86, "label86");
  GLADE_HOOKUP_OBJECT (Admin, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Admin, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (Admin, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (Admin, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (Admin, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (Admin, label89, "label89");
  GLADE_HOOKUP_OBJECT (Admin, label90, "label90");
  GLADE_HOOKUP_OBJECT (Admin, entry34, "entry34");
  GLADE_HOOKUP_OBJECT (Admin, label103, "label103");
  GLADE_HOOKUP_OBJECT (Admin, label99, "label99");
  GLADE_HOOKUP_OBJECT (Admin, label93, "label93");
  GLADE_HOOKUP_OBJECT (Admin, label94, "label94");
  GLADE_HOOKUP_OBJECT (Admin, label92, "label92");
  GLADE_HOOKUP_OBJECT (Admin, label104, "label104");
  GLADE_HOOKUP_OBJECT (Admin, label101, "label101");
  GLADE_HOOKUP_OBJECT (Admin, button23, "button23");
  GLADE_HOOKUP_OBJECT (Admin, button22, "button22");
  GLADE_HOOKUP_OBJECT (Admin, erreur2, "erreur2");
  GLADE_HOOKUP_OBJECT (Admin, combobox8, "combobox8");
  GLADE_HOOKUP_OBJECT (Admin, label87, "label87");
  GLADE_HOOKUP_OBJECT (Admin, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (Admin, button24, "button24");
  GLADE_HOOKUP_OBJECT (Admin, NB_M, "NB_M");
  GLADE_HOOKUP_OBJECT (Admin, NB_C, "NB_C");
  GLADE_HOOKUP_OBJECT (Admin, NB_A_F, "NB_A_F");
  GLADE_HOOKUP_OBJECT (Admin, NB_A_H, "NB_A_H");
  GLADE_HOOKUP_OBJECT (Admin, NB_A, "NB_A");
  GLADE_HOOKUP_OBJECT (Admin, label88, "label88");
  GLADE_HOOKUP_OBJECT (Admin, label54, "label54");

  return Admin;
}

